name: Deploy to DreamHost via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload Website to DreamHost
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.food.wire-tech.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /home/foodwtsiteftp/food.wire-tech.net
